//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevAssignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thing
    {
        public Nullable<double> item_ID { get; set; }
        public Nullable<double> category_ID { get; set; }
        public string title { get; set; }
        public string timeCommitment { get; set; }
        public bool soloActivity { get; set; }
        public string image { get; set; }
        public string shortDesc { get; set; }
        public string longDesc { get; set; }
    }
}
